backendSvc:
  ports:
  - nodePort: 31000
    port: 3000
    protocol: TCP
    targetPort: 3000
  type: NodePort
kubernetesClusterDomain: cluster.local
wezvafrontendapp:
  nodeSelector: {}
  replicas: 1
  tolerations: []
  topologySpreadConstraints: []
  wezvafrontendapp:
    image:
      repository: 303255670930.dkr.ecr.ap-south-1.amazonaws.com/wezvatechbackend
      tag: fb11
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 400m
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 128Mi
